#ifndef SEGGER_RTT_CONF_H
#define SEGGER_RTT_CONF_H

#define SEGGER_RTT_MAX_NUM_UP_BUFFERS    2
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS  1
#define SEGGER_RTT_BUFFER_SIZE_UP        512
#define SEGGER_RTT_BUFFER_SIZE_DOWN      256
#define SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL 0

#define SEGGER_RTT_PRINTF_BUFFER_SIZE    128

#endif