#* CPack
set(CPACK_VERBATIM_VARIABLES YES)
set(CPACK_PACKAGE_NAME "StaticMbedOS-${MBED_TARGET}")
set(CPACK_PACKAGE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/dist")
set(CPACK_PACKAGE_CONTACT "syoch64@gmail.com")
set(CPACK_GENERATOR "DEB;TGZ")

# deb specific
# MBED_TARGET_LOWER = MBED_TARGET.lower()
string(TOLOWER ${MBED_TARGET} MBED_TARGET_LOWER)

set(CPACK_DEBIAN_PACKAGE_NAME "static-mbed-os-${MBED_TARGET_LOWER}")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "syoch")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "static-mbed-os-core (>=1.0.0)")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "StaticMbedOS for ${MBED_TARGET}")
set(CPACK_DEBIAN_PACKAGE_SECTION "libs")

include(InstallRequiredSystemLibraries)
include(CPack)
