#ifndef SEGGER_RTT_CONF_H
#define SEGGER_RTT_CONF_H

#define SEGGER_RTT_MAX_NUM_UP_BUFFERS    4
#define SEGGER_RTT_MAX_NUM_DOWN_BUFFERS  3
#define SEGGER_RTT_BUFFER_SIZE_UP        1024
#define SEGGER_RTT_BUFFER_SIZE_DOWN      512
#define SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL 1

#define SEGGER_RTT_PRINTF_BUFFER_SIZE    256

#endif